#!/usr/bin/env python3
"""
coreprotect-ekaii bench harness.

Runs the same workload across three backends:
  A) SQLite (CoreProtect's default file-based backend)
  B) PostgreSQL flat schema (no partitioning, no lz4)
  C) PostgreSQL partitioned + BRIN(time) + partial idx + lz4 (the ekaii fork's PR4 default)

Workload (per backend):
  1. Apply the matching DDL.
  2. SEED phase: insert N rows into co_block spanning ~90 days back from now.
  3. INSERT phase: time how long it takes to insert another K rows (rows/sec).
  4. RANGE-SCAN phase: time R range scans (different filters), report median + p95.
  5. RETENTION phase: delete everything older than 30 days. Time + rows + (PG)
     partitions dropped. For the partitioned backend this is DROP TABLE; for the
     others it's chunked DELETE in 5,000-row batches.
  6. FOOTPRINT: size of the data after seed (file bytes for SQLite; pg_total_relation_size
     for PG). Recorded both raw and after VACUUM/ANALYZE for PG.

Output: bench/results/<timestamp>.json + Markdown summary printed to stdout.

Usage: python3 bench.py --rows 100000 --extra-inserts 10000 --scans 25
"""

import argparse
import json
import os
import random
import statistics
import subprocess
import sys
import sqlite3
import time
from datetime import datetime, timezone
from pathlib import Path

import psycopg2
import psycopg2.extras

ROOT = Path(__file__).resolve().parent
RESULTS_DIR = ROOT / "results"
RESULTS_DIR.mkdir(exist_ok=True)

PG_CONTAINER = "cp-bench-pg"
PG_PORT = 25433  # avoid clashing with the smoke pg on 25432


# ---------------- DDL ----------------

PG_FLAT_DDL = """
DROP SCHEMA public CASCADE; CREATE SCHEMA public;
CREATE TABLE co_block (
    rowid bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    time integer, "user" integer, wid integer, x integer, y integer, z integer,
    type integer, data integer, meta bytea, blockdata bytea,
    action smallint, rolled_back smallint
);
CREATE INDEX block_index           ON co_block (wid, x, z, time);
CREATE INDEX block_user_index      ON co_block ("user", time);
CREATE INDEX block_type_index      ON co_block (type, time);
CREATE INDEX block_time_index_btree ON co_block (time);
"""

PG_PART_DDL = """
DROP SCHEMA public CASCADE; CREATE SCHEMA public;
CREATE TABLE co_block (
    rowid bigint GENERATED BY DEFAULT AS IDENTITY,
    time integer NOT NULL,
    "user" integer, wid integer, x integer, y integer, z integer,
    type integer, data integer, meta bytea, blockdata bytea,
    action smallint, rolled_back smallint NOT NULL DEFAULT 0,
    PRIMARY KEY (rowid, time)
) PARTITION BY RANGE (time);
CREATE TABLE co_block_default PARTITION OF co_block DEFAULT;
"""

# Indices for partitioned PG; created after partitions exist.
PG_PART_INDICES = [
    'CREATE INDEX block_index           ON co_block (wid, x, z, time)',
    'CREATE INDEX block_user_index      ON co_block ("user", time)',
    'CREATE INDEX block_type_index      ON co_block (type, time)',
    'CREATE INDEX block_time_brin       ON co_block USING BRIN (time) WITH (pages_per_range = 32)',
    'CREATE INDEX block_rb_partial_idx  ON co_block (wid, x, z, time) WHERE rolled_back = 0',
]
PG_PART_LZ4 = [
    'ALTER TABLE co_block ALTER COLUMN meta SET COMPRESSION lz4',
    'ALTER TABLE co_block ALTER COLUMN blockdata SET COMPRESSION lz4',
]

SQLITE_DDL = """
CREATE TABLE co_block (
    time INTEGER, user INTEGER, wid INTEGER, x INTEGER, y INTEGER, z INTEGER,
    type INTEGER, data INTEGER, meta BLOB, blockdata BLOB, action INTEGER, rolled_back INTEGER
);
CREATE INDEX block_index      ON co_block (wid, x, z, time);
CREATE INDEX block_user_index ON co_block (user, time);
CREATE INDEX block_type_index ON co_block (type, time);
CREATE INDEX block_time_index ON co_block (time);
"""


# ---------------- Helpers ----------------

_NBT_TEMPLATE = (
    b"\x00\x00\x00" + b"id:minecraft:" + b"\x00" * 8
    + b"Damage" + b"\x00" * 6 + b"RepairCost" + b"\x00" * 12
    + b"display" + b"\x00" * 8 + b"Enchantments" + b"\x00" * 10
)
def synthetic_blob(seed):
    # Real NBT is mostly repeated tag names + null padding; lz4 typically gets 4-8x.
    rnd = random.Random(seed)
    template = bytearray(_NBT_TEMPLATE)
    # Sprinkle a few varying bytes so dedup-style codecs don't flatten everything.
    for _ in range(6):
        template[rnd.randrange(len(template))] = rnd.randrange(256)
    return bytes(template)


def gen_rows(n, base_now, span_seconds):
    """Generate n synthetic block rows spread across the past span_seconds."""
    rng = random.Random(0xC0DEC0DE)
    rows = []
    for i in range(n):
        t = base_now - rng.randrange(span_seconds)
        wid = rng.randrange(4)
        x = rng.randrange(-2000, 2000)
        y = rng.randrange(-64, 320)
        z = rng.randrange(-2000, 2000)
        typ = rng.randrange(1, 200)
        data = rng.randrange(0, 16)
        meta = synthetic_blob(i)
        blockdata = synthetic_blob(i + 0xBEEF)
        action = rng.randrange(0, 4)
        rolled = 0
        rows.append((t, 1, wid, x, y, z, typ, data, meta, blockdata, action, rolled))
    return rows


def percentile(xs, p):
    if not xs:
        return 0.0
    sorted_xs = sorted(xs)
    k = max(0, min(len(sorted_xs) - 1, int(len(sorted_xs) * p / 100)))
    return sorted_xs[k]


def run(cmd, **kw):
    return subprocess.run(cmd, check=False, **kw)


def start_pg():
    run(["docker", "rm", "-f", PG_CONTAINER], capture_output=True)
    out = run(
        [
            "docker", "run", "-d", "--rm",
            "--name", PG_CONTAINER,
            "-p", f"{PG_PORT}:5432",
            "-e", "POSTGRES_PASSWORD=cp",
            "-e", "POSTGRES_USER=cp",
            "-e", "POSTGRES_DB=coreprotect",
            "postgres:16",
        ],
        capture_output=True, text=True,
    )
    if out.returncode != 0:
        print("docker run failed:", out.stderr, file=sys.stderr)
        sys.exit(1)
    # Wait for PG ready (probe pg_isready, then probe an actual psycopg connection).
    for _ in range(60):
        time.sleep(0.5)
        ready = run(
            ["docker", "exec", PG_CONTAINER, "pg_isready", "-U", "cp", "-d", "coreprotect"],
            capture_output=True,
        )
        if ready.returncode == 0:
            try:
                with pg_conn() as c, c.cursor() as cur:
                    cur.execute("SELECT 1")
                    cur.fetchone()
                return
            except Exception:
                pass
    print("postgres did not become ready", file=sys.stderr)
    sys.exit(1)


def stop_pg():
    run(["docker", "stop", PG_CONTAINER], capture_output=True)


def pg_conn():
    return psycopg2.connect(
        host="127.0.0.1",
        port=PG_PORT,
        dbname="coreprotect",
        user="cp",
        password="cp",
        connect_timeout=5,
    )


def pg_apply(ddl):
    with pg_conn() as c, c.cursor() as cur:
        cur.execute(ddl)
        c.commit()


def pg_exec(sql):
    with pg_conn() as c, c.cursor() as cur:
        cur.execute(sql)
        c.commit()


def pg_seed_partitions(rows, base_now):
    """Create the partitions needed to cover the time span of `rows`."""
    # week starts (Mon UTC) covering all rows
    times = sorted(r[0] for r in rows)
    # Walk from earliest to latest in 7-day steps from epoch-aligned Monday.
    earliest = times[0]
    latest = times[-1] + 86400
    week_secs = 7 * 86400
    # Align to Mon 00:00 UTC: 1970-01-05 was a Monday → epoch 345600
    EPOCH_MON = 345600
    start = EPOCH_MON + ((earliest - EPOCH_MON) // week_secs) * week_secs
    end = EPOCH_MON + ((latest - EPOCH_MON) // week_secs + 1) * week_secs
    created = 0
    with pg_conn() as c, c.cursor() as cur:
        cur.execute("ALTER TABLE co_block DETACH PARTITION co_block_default")
        try:
            t = start
            while t < end:
                lo = t
                hi = t + week_secs
                # Generate a stable suffix.
                yyyy_ww = datetime.fromtimestamp(lo, tz=timezone.utc).strftime("y%Yw%V")
                cur.execute(
                    f"CREATE TABLE IF NOT EXISTS co_block_{yyyy_ww} "
                    f"PARTITION OF co_block FOR VALUES FROM ({lo}) TO ({hi})"
                )
                created += 1
                t += week_secs
        finally:
            cur.execute("ALTER TABLE co_block ATTACH PARTITION co_block_default DEFAULT")
        c.commit()
    return created


def pg_insert_executemany(rows):
    with pg_conn() as c, c.cursor() as cur:
        psycopg2.extras.execute_batch(
            cur,
            'INSERT INTO co_block (time,"user",wid,x,y,z,type,data,meta,blockdata,action,rolled_back) '
            "VALUES (%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s)",
            rows,
            page_size=2000,
        )
        c.commit()


def pg_chunked_delete(before_unix, table="co_block"):
    deleted = 0
    while True:
        with pg_conn() as c, c.cursor() as cur:
            cur.execute(
                f"DELETE FROM {table} WHERE ctid IN ("
                f"  SELECT ctid FROM {table} WHERE time < %s ORDER BY time ASC LIMIT 5000"
                ")",
                (before_unix,),
            )
            n = cur.rowcount
            c.commit()
        if n <= 0:
            break
        deleted += n
    return deleted


def pg_drop_old_partitions(before_unix):
    dropped = 0
    with pg_conn() as c, c.cursor() as cur:
        cur.execute(
            "SELECT c.relname, pg_get_expr(c.relpartbound, c.oid) "
            "FROM pg_inherits i "
            "JOIN pg_class p ON p.oid = i.inhparent "
            "JOIN pg_class c ON c.oid = i.inhrelid "
            "WHERE p.relname = 'co_block'"
        )
        rows = cur.fetchall()
    for name, bounds in rows:
        if bounds is None or "DEFAULT" in bounds.upper():
            continue
        # bounds e.g. "FOR VALUES FROM ('1745366400') TO ('1745971200')"
        import re
        m = re.search(r"TO\s*\(\s*'?(\d+)'?\s*\)", bounds)
        if not m:
            continue
        upper = int(m.group(1))
        if upper <= before_unix:
            with pg_conn() as c2, c2.cursor() as cur2:
                cur2.execute(f"DROP TABLE IF EXISTS {name}")
                c2.commit()
            dropped += 1
    return dropped


def pg_total_size(table="co_block"):
    """Total relation size INCLUDING attached partitions (pg_total_relation_size of the parent
    only returns the parent's own bytes, which is ~0 for a partitioned table)."""
    sql = (
        "WITH RECURSIVE descendants AS ("
        "  SELECT oid FROM pg_class WHERE relname = %s "
        "  UNION ALL "
        "  SELECT i.inhrelid FROM pg_inherits i JOIN descendants d ON i.inhparent = d.oid"
        ") SELECT COALESCE(SUM(pg_total_relation_size(oid)), 0) FROM descendants"
    )
    with pg_conn() as c, c.cursor() as cur:
        cur.execute(sql, (table,))
        row = cur.fetchone()
    return int(row[0]) if row else 0


def pg_indexes_size(table="co_block"):
    sql = (
        "WITH RECURSIVE descendants AS ("
        "  SELECT oid FROM pg_class WHERE relname = %s "
        "  UNION ALL "
        "  SELECT i.inhrelid FROM pg_inherits i JOIN descendants d ON i.inhparent = d.oid"
        ") SELECT COALESCE(SUM(pg_indexes_size(oid)), 0) FROM descendants"
    )
    with pg_conn() as c, c.cursor() as cur:
        cur.execute(sql, (table,))
        row = cur.fetchone()
    return int(row[0]) if row else 0


# ---------------- Scenarios ----------------

def scenario_sqlite(args, base_now):
    db_path = ROOT / "results" / "_sqlite.db"
    if db_path.exists():
        db_path.unlink()
    conn = sqlite3.connect(str(db_path))
    cur = conn.cursor()
    cur.executescript(SQLITE_DDL)
    conn.commit()

    rows = gen_rows(args.rows, base_now, 90 * 86400)

    # Seed
    t0 = time.perf_counter()
    cur.executemany(
        "INSERT INTO co_block (time, user, wid, x, y, z, type, data, meta, blockdata, action, rolled_back)"
        " VALUES (?,?,?,?,?,?,?,?,?,?,?,?)",
        rows,
    )
    conn.commit()
    seed_ms = (time.perf_counter() - t0) * 1000

    # Insert phase
    extra = gen_rows(args.extra_inserts, base_now, 86400)
    t0 = time.perf_counter()
    cur.executemany(
        "INSERT INTO co_block (time, user, wid, x, y, z, type, data, meta, blockdata, action, rolled_back)"
        " VALUES (?,?,?,?,?,?,?,?,?,?,?,?)",
        extra,
    )
    conn.commit()
    ins_ms = (time.perf_counter() - t0) * 1000
    insert_throughput = args.extra_inserts / (ins_ms / 1000.0)

    # Range scans
    scans = []
    rng = random.Random(42)
    for i in range(args.scans):
        wid = rng.randrange(4)
        time_lo = base_now - rng.randrange(7 * 86400, 60 * 86400)
        t0 = time.perf_counter()
        cur.execute(
            "SELECT rowid, time, x, y, z, type FROM co_block "
            "INDEXED BY block_index WHERE wid=? AND time >= ? ORDER BY time DESC LIMIT 1000",
            (wid, time_lo),
        )
        cur.fetchall()
        scans.append((time.perf_counter() - t0) * 1000)

    # Footprint
    conn.close()
    file_bytes = db_path.stat().st_size

    # Retention: chunked DELETE (mimics SqliteDialect.purgeOldRows path)
    cutoff = base_now - 30 * 86400
    conn = sqlite3.connect(str(db_path))
    cur = conn.cursor()
    t0 = time.perf_counter()
    deleted_total = 0
    while True:
        cur.execute(
            "DELETE FROM co_block WHERE rowid IN ("
            "  SELECT rowid FROM co_block WHERE time < ? ORDER BY time ASC LIMIT 5000"
            ")",
            (cutoff,),
        )
        n = cur.rowcount
        conn.commit()
        if n <= 0:
            break
        deleted_total += n
    ret_ms = (time.perf_counter() - t0) * 1000
    conn.close()

    return {
        "scenario": "sqlite",
        "rows_seeded": args.rows,
        "seed_ms": round(seed_ms, 2),
        "insert_extra_rows": args.extra_inserts,
        "insert_ms": round(ins_ms, 2),
        "insert_rows_per_sec": round(insert_throughput, 1),
        "scan_count": args.scans,
        "scan_p50_ms": round(percentile(scans, 50), 3),
        "scan_p95_ms": round(percentile(scans, 95), 3),
        "scan_max_ms": round(max(scans), 3),
        "footprint_bytes": file_bytes,
        "retention_ms": round(ret_ms, 2),
        "retention_rows_deleted": deleted_total,
        "retention_partitions_dropped": 0,
    }


def scenario_pg(args, base_now, label, partitioned, lz4):
    pg_apply(PG_PART_DDL if partitioned else PG_FLAT_DDL)

    rows = gen_rows(args.rows, base_now, 90 * 86400)

    if partitioned:
        pg_seed_partitions(rows, base_now)

    if partitioned:
        # Indices created on parent propagate to all partitions.
        for sql in PG_PART_INDICES:
            pg_exec(sql)
        if lz4:
            for sql in PG_PART_LZ4:
                pg_exec(sql)

    # Seed
    t0 = time.perf_counter()
    pg_insert_executemany(rows)
    seed_ms = (time.perf_counter() - t0) * 1000

    # ANALYZE for fair planning.
    pg_exec("ANALYZE co_block")

    # Insert phase
    extra = gen_rows(args.extra_inserts, base_now, 86400)
    t0 = time.perf_counter()
    pg_insert_executemany(extra)
    ins_ms = (time.perf_counter() - t0) * 1000
    insert_throughput = args.extra_inserts / (ins_ms / 1000.0)

    pg_exec("ANALYZE co_block")

    # Range scans
    scans = []
    rng = random.Random(42)
    with pg_conn() as c, c.cursor() as cur:
        for i in range(args.scans):
            wid = rng.randrange(4)
            time_lo = base_now - rng.randrange(7 * 86400, 60 * 86400)
            t0 = time.perf_counter()
            cur.execute(
                'SELECT rowid, time, x, y, z, type FROM co_block '
                'WHERE wid=%s AND time >= %s ORDER BY time DESC LIMIT 1000',
                (wid, time_lo),
            )
            cur.fetchall()
            scans.append((time.perf_counter() - t0) * 1000)

    # Footprint
    table_bytes = pg_total_size("co_block")
    indexes_bytes = pg_indexes_size("co_block")

    # Retention: drop partitions on partitioned scenario, chunked DELETE on flat
    cutoff = base_now - 30 * 86400
    t0 = time.perf_counter()
    if partitioned:
        partitions_dropped = pg_drop_old_partitions(cutoff)
        # Sweep stragglers in default partition.
        deleted = pg_chunked_delete(cutoff, "co_block_default")
    else:
        partitions_dropped = 0
        deleted = pg_chunked_delete(cutoff, "co_block")
    ret_ms = (time.perf_counter() - t0) * 1000

    return {
        "scenario": label,
        "rows_seeded": args.rows,
        "seed_ms": round(seed_ms, 2),
        "insert_extra_rows": args.extra_inserts,
        "insert_ms": round(ins_ms, 2),
        "insert_rows_per_sec": round(insert_throughput, 1),
        "scan_count": args.scans,
        "scan_p50_ms": round(percentile(scans, 50), 3),
        "scan_p95_ms": round(percentile(scans, 95), 3),
        "scan_max_ms": round(max(scans), 3),
        "footprint_bytes": table_bytes,
        "footprint_indexes_bytes": indexes_bytes,
        "retention_ms": round(ret_ms, 2),
        "retention_rows_deleted": deleted,
        "retention_partitions_dropped": partitions_dropped,
    }


# ---------------- Driver ----------------

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--rows", type=int, default=100_000, help="seed rows in co_block (default 100k)")
    ap.add_argument("--extra-inserts", type=int, default=10_000, help="rows for the insert-phase timing")
    ap.add_argument("--scans", type=int, default=25)
    ap.add_argument("--skip-pg", action="store_true")
    ap.add_argument("--skip-sqlite", action="store_true")
    args = ap.parse_args()

    print(f"# coreprotect-ekaii bench — rows={args.rows} extra={args.extra_inserts} scans={args.scans}")
    print(f"# started {datetime.now(tz=timezone.utc).isoformat()}")
    base_now = int(time.time())

    results = []

    if not args.skip_sqlite:
        print(">> SQLite ...", flush=True)
        results.append(scenario_sqlite(args, base_now))

    if not args.skip_pg:
        try:
            start_pg()
            print(">> PG flat (no partitioning, no lz4) ...", flush=True)
            results.append(scenario_pg(args, base_now, "pg-flat", partitioned=False, lz4=False))
            print(">> PG partitioned + BRIN + lz4 ...", flush=True)
            results.append(scenario_pg(args, base_now, "pg-partitioned-lz4", partitioned=True, lz4=True))
        finally:
            stop_pg()

    # Persist
    out_path = RESULTS_DIR / f"bench-{datetime.now(tz=timezone.utc).strftime('%Y%m%dT%H%M%SZ')}.json"
    with open(out_path, "w") as f:
        json.dump({"args": vars(args), "results": results}, f, indent=2)

    # Print summary
    print()
    print("| scenario | seed (ms) | inserts (rows/sec) | scan p50 (ms) | scan p95 (ms) | retention (ms) | rows del | parts dropped | data (MiB) | idx (MiB) |")
    print("|---|--:|--:|--:|--:|--:|--:|--:|--:|--:|")
    for r in results:
        size_mib = r["footprint_bytes"] / (1024 * 1024)
        idx_mib = r.get("footprint_indexes_bytes", 0) / (1024 * 1024)
        print(
            f"| {r['scenario']} "
            f"| {r['seed_ms']:.0f} "
            f"| {r['insert_rows_per_sec']:.0f} "
            f"| {r['scan_p50_ms']:.2f} "
            f"| {r['scan_p95_ms']:.2f} "
            f"| {r['retention_ms']:.0f} "
            f"| {r['retention_rows_deleted']} "
            f"| {r['retention_partitions_dropped']} "
            f"| {size_mib:.1f} "
            f"| {idx_mib:.1f} |"
        )
    print()
    print(f"# results: {out_path}")


if __name__ == "__main__":
    main()
