package net.coreprotect.database.dialect;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.Statement;

import net.coreprotect.consumer.Consumer;
import net.coreprotect.database.Backend;

/**
 * DuckDB dialect — embedded, single-file, columnar, in-process.
 *
 * <p>Why ship it: DuckDB combines SQLite's "single file, no install" deployment
 * model with PG-class performance for analytical queries. For CoreProtect this
 * means we get range-scan speed close to PG-flat with SQLite-like footprint and
 * no IPC overhead at all. DuckDB's storage is columnar with built-in zonemap
 * indexing on every column (BRIN-equivalent, no DDL needed) and per-column
 * lz4/zstd compression on disk.</p>
 *
 * <p>Differences from PG that matter at the SQL level:</p>
 * <ul>
 *   <li>Identity columns: DuckDB uses <code>BIGINT GENERATED ALWAYS AS IDENTITY</code>
 *       (since 0.10). We use <code>BY DEFAULT</code> for the same reason as PG —
 *       the legacy code paths sometimes bind rowid explicitly.</li>
 *   <li><code>"user"</code> is NOT reserved in DuckDB — we still quote it everywhere
 *       so the SQL is portable, but no translator is required.</li>
 *   <li><code>LIMIT n, m</code> — DuckDB accepts both <code>LIMIT m OFFSET n</code>
 *       and the MySQL-style <code>LIMIT n, m</code> as of 0.9. No translator needed.</li>
 *   <li>Bytea ⇒ <code>BLOB</code>. Smallint ⇒ <code>SMALLINT</code>.</li>
 *   <li>Single-process write lock: only one writer connection at a time. Hikari
 *       <code>maximumPoolSize=1</code> on this backend.</li>
 *   <li>No partitioning: zonemap pruning handles the BRIN role natively per column.</li>
 * </ul>
 */
public final class DuckDBDialect implements Dialect {

    @Override
    public Backend backend() { return Backend.DUCKDB; }

    @Override
    public String driverClassName() { return "org.duckdb.DuckDBDriver"; }

    @Override
    public String jdbcUrl(String host, int port, String database) {
        // For DuckDB, host == file path, port unused, database unused.
        return "jdbc:duckdb:" + host;
    }

    @Override
    public void beginTransaction(Statement statement) {
        try { statement.executeUpdate("BEGIN TRANSACTION"); }
        catch (Exception e) { e.printStackTrace(); }
    }

    @Override
    public void commitTransaction(Statement statement) throws Exception {
        try { statement.executeUpdate("COMMIT"); }
        catch (Exception e) { e.printStackTrace(); }
        finally {
            Consumer.transacting = false;
            Consumer.interrupt = false;
        }
    }

    @Override
    public void performCheckpoint(Statement statement) throws SQLException {
        // DuckDB checkpoints automatically; nothing to do.
    }

    @Override
    public void createSchema(Statement statement, String prefix) throws SQLException {
        // Tables. DuckDB's identity column is BIGINT IDENTITY since 0.10; we use
        // GENERATED BY DEFAULT so explicit rowid binds (legacy paths) still work.
        statement.executeUpdate("CREATE TABLE IF NOT EXISTS " + prefix + "art_map (rowid BIGINT PRIMARY KEY, id INTEGER, art VARCHAR)");
        // co_block: clustered by time so DuckDB's zonemap on the implicit rowgroup boundary
        // gets tight time-range pruning. PRIMARY KEY (time, rowid) for the same reason as PG.
        statement.executeUpdate("CREATE TABLE IF NOT EXISTS " + prefix + "block (rowid BIGINT, time INTEGER NOT NULL, \"user\" INTEGER, wid INTEGER, x INTEGER, y INTEGER, z INTEGER, type INTEGER, data INTEGER, meta BLOB, blockdata BLOB, action SMALLINT, rolled_back SMALLINT NOT NULL DEFAULT 0, PRIMARY KEY (time, rowid))");
        statement.executeUpdate("CREATE TABLE IF NOT EXISTS " + prefix + "container (rowid BIGINT, time INTEGER NOT NULL, \"user\" INTEGER, wid INTEGER, x INTEGER, y INTEGER, z INTEGER, type INTEGER, data INTEGER, amount INTEGER, metadata BLOB, action SMALLINT, rolled_back SMALLINT NOT NULL DEFAULT 0, PRIMARY KEY (time, rowid))");
        statement.executeUpdate("CREATE TABLE IF NOT EXISTS " + prefix + "chat (rowid BIGINT PRIMARY KEY, time INTEGER, \"user\" INTEGER, wid INTEGER, x INTEGER, y INTEGER, z INTEGER, message VARCHAR)");
        statement.executeUpdate("CREATE TABLE IF NOT EXISTS " + prefix + "command (rowid BIGINT PRIMARY KEY, time INTEGER, \"user\" INTEGER, wid INTEGER, x INTEGER, y INTEGER, z INTEGER, message VARCHAR)");
        statement.executeUpdate("CREATE TABLE IF NOT EXISTS " + prefix + "item (rowid BIGINT PRIMARY KEY, time INTEGER, \"user\" INTEGER, wid INTEGER, x INTEGER, y INTEGER, z INTEGER, type INTEGER, data BLOB, amount INTEGER, action SMALLINT, rolled_back SMALLINT)");
        statement.executeUpdate("CREATE TABLE IF NOT EXISTS " + prefix + "database_lock (rowid BIGINT PRIMARY KEY, status SMALLINT, time INTEGER)");
        statement.executeUpdate("CREATE TABLE IF NOT EXISTS " + prefix + "entity (rowid BIGINT PRIMARY KEY, time INTEGER, data BLOB)");
        statement.executeUpdate("CREATE TABLE IF NOT EXISTS " + prefix + "entity_map (rowid BIGINT PRIMARY KEY, id INTEGER, entity VARCHAR)");
        statement.executeUpdate("CREATE TABLE IF NOT EXISTS " + prefix + "material_map (rowid BIGINT PRIMARY KEY, id INTEGER, material VARCHAR)");
        statement.executeUpdate("CREATE TABLE IF NOT EXISTS " + prefix + "blockdata_map (rowid BIGINT PRIMARY KEY, id INTEGER, data VARCHAR)");
        statement.executeUpdate("CREATE TABLE IF NOT EXISTS " + prefix + "session (rowid BIGINT PRIMARY KEY, time INTEGER, \"user\" INTEGER, wid INTEGER, x INTEGER, y INTEGER, z INTEGER, action SMALLINT)");
        statement.executeUpdate("CREATE TABLE IF NOT EXISTS " + prefix + "sign (rowid BIGINT PRIMARY KEY, time INTEGER, \"user\" INTEGER, wid INTEGER, x INTEGER, y INTEGER, z INTEGER, action SMALLINT, color INTEGER, color_secondary INTEGER, data SMALLINT, waxed SMALLINT, face SMALLINT, line_1 VARCHAR, line_2 VARCHAR, line_3 VARCHAR, line_4 VARCHAR, line_5 VARCHAR, line_6 VARCHAR, line_7 VARCHAR, line_8 VARCHAR)");
        statement.executeUpdate("CREATE TABLE IF NOT EXISTS " + prefix + "skull (rowid BIGINT PRIMARY KEY, time INTEGER, owner VARCHAR, skin VARCHAR)");
        statement.executeUpdate("CREATE TABLE IF NOT EXISTS " + prefix + "user (rowid BIGINT PRIMARY KEY, time INTEGER, \"user\" VARCHAR, uuid VARCHAR)");
        statement.executeUpdate("CREATE TABLE IF NOT EXISTS " + prefix + "username_log (rowid BIGINT PRIMARY KEY, time INTEGER, uuid VARCHAR, \"user\" VARCHAR)");
        statement.executeUpdate("CREATE TABLE IF NOT EXISTS " + prefix + "version (rowid BIGINT PRIMARY KEY, time INTEGER, version VARCHAR)");
        statement.executeUpdate("CREATE TABLE IF NOT EXISTS " + prefix + "world (rowid BIGINT PRIMARY KEY, id INTEGER, world VARCHAR)");

        // DuckDB indices: column zonemaps are automatic; B-tree indices help point lookups.
        idx(statement, prefix + "art_map",        "art_map_id_idx",          "(id)");
        idx(statement, prefix + "block",          "block_index",             "(wid, x, z, time)");
        idx(statement, prefix + "block",          "block_user_index",        "(\"user\", time)");
        idx(statement, prefix + "block",          "block_type_index",        "(type, time)");
        idx(statement, prefix + "blockdata_map",  "blockdata_map_id_idx",    "(id)");
        idx(statement, prefix + "chat",           "chat_user_index",         "(\"user\", time)");
        idx(statement, prefix + "chat",           "chat_wid_index",          "(wid, x, z, time)");
        idx(statement, prefix + "command",        "command_user_index",      "(\"user\", time)");
        idx(statement, prefix + "command",        "command_wid_index",       "(wid, x, z, time)");
        idx(statement, prefix + "container",      "container_index",         "(wid, x, z, time)");
        idx(statement, prefix + "container",      "container_user_index",    "(\"user\", time)");
        idx(statement, prefix + "container",      "container_type_index",    "(type, time)");
        idx(statement, prefix + "item",           "item_index",              "(wid, x, z, time)");
        idx(statement, prefix + "item",           "item_user_index",         "(\"user\", time)");
        idx(statement, prefix + "item",           "item_type_index",         "(type, time)");
        idx(statement, prefix + "entity_map",     "entity_map_id_idx",       "(id)");
        idx(statement, prefix + "material_map",   "material_map_id_idx",     "(id)");
        idx(statement, prefix + "session",        "session_index",           "(wid, x, z, time)");
        idx(statement, prefix + "session",        "session_action_index",    "(action, time)");
        idx(statement, prefix + "session",        "session_user_index",      "(\"user\", time)");
        idx(statement, prefix + "sign",           "sign_index",              "(wid, x, z, time)");
        idx(statement, prefix + "sign",           "sign_user_index",         "(\"user\", time)");
        idx(statement, prefix + "user",           "user_user_idx",           "(\"user\")");
        idx(statement, prefix + "user",           "user_uuid_idx",           "(uuid)");
        idx(statement, prefix + "username_log",   "username_log_uuid_idx",   "(uuid, \"user\")");
        idx(statement, prefix + "world",          "world_id_idx",            "(id)");
    }

    private static void idx(Statement s, String table, String name, String cols) throws SQLException {
        try {
            s.executeUpdate("CREATE INDEX IF NOT EXISTS " + name + " ON " + table + " " + cols);
        }
        catch (SQLException ignored) { /* DuckDB rejects index recreation on some versions; safe to skip */ }
    }

    @Override
    public int purgeOldRows(Connection connection, String prefixedTable, long beforeUnixSeconds, int chunkLimit) throws SQLException {
        // DuckDB DELETE is fast (rowgroup-aware); a single statement is fine, but we still
        // bound it to keep retention sweep latency bounded on huge tables.
        String sql = "DELETE FROM " + prefixedTable
                   + " WHERE rowid IN (SELECT rowid FROM " + prefixedTable
                   + " WHERE time < ? ORDER BY time ASC LIMIT ?)";
        try (PreparedStatement ps = connection.prepareStatement(sql)) {
            ps.setLong(1, beforeUnixSeconds);
            ps.setInt(2, chunkLimit);
            return ps.executeUpdate();
        }
    }

    @Override
    public boolean supportsReturningClause() { return true; }

    @Override
    public boolean supportsOnConflict() { return true; }
}
