package net.coreprotect.database.dialect;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.Statement;

import net.coreprotect.config.Config;
import net.coreprotect.consumer.Consumer;
import net.coreprotect.database.Backend;

/**
 * PostgreSQL dialect.
 *
 * <p>DDL choices that matter:</p>
 * <ul>
 *   <li>{@code rowid} stays the column name to keep runtime SQL identical to
 *       MySQL/SQLite. Postgres reserves no such word.</li>
 *   <li>Identity columns: {@code GENERATED BY DEFAULT AS IDENTITY} so legacy
 *       INSERTs that explicitly bind {@code rowid} (database_lock seed row,
 *       manual fix-ups) still work.</li>
 *   <li>{@code mediumblob} / {@code blob} → {@code bytea}.</li>
 *   <li>{@code tinyint} → {@code smallint}. CoreProtect reads these as int
 *       via {@code ResultSet.getInt}, so widening is invisible.</li>
 *   <li>BRIN(time) on co_block + co_container — ~30 KB index for a 100M-row
 *       table because {@code time} is monotonically increasing.</li>
 *   <li>Partial index on {@code rolled_back = 0} cuts the rollback-lookup
 *       index in half once stale rows accumulate.</li>
 *   <li>Optional {@code lz4} compression on {@code meta}/{@code blockdata}
 *       /{@code metadata}/{@code data} (PG14+). Falls back to default
 *       {@code pglz} on older servers.</li>
 *   <li>Optional time-range partitioning on co_block + co_container, weekly.
 *       When enabled, retention drops whole partitions in O(1) instead of
 *       chunked DELETE.</li>
 * </ul>
 */
public final class PostgresDialect implements Dialect {

    /** Column name we partition on. Kept here so PartitionService and DDL agree. */
    public static final String PARTITION_KEY = "time";
    /** Tables we partition. */
    public static final String[] PARTITIONED_TABLES = { "block", "container" };

    @Override
    public Backend backend() { return Backend.POSTGRES; }

    @Override
    public String driverClassName() { return "org.postgresql.Driver"; }

    @Override
    public String jdbcUrl(String host, int port, String database) {
        return "jdbc:postgresql://" + host + ":" + port + "/" + database;
    }

    @Override
    public void beginTransaction(Statement statement) {
        try { statement.executeUpdate("BEGIN"); }
        catch (Exception e) { e.printStackTrace(); }
    }

    @Override
    public void commitTransaction(Statement statement) throws Exception {
        try { statement.executeUpdate("COMMIT"); }
        catch (Exception e) { e.printStackTrace(); }
        finally {
            Consumer.transacting = false;
            Consumer.interrupt = false;
        }
    }

    @Override
    public void performCheckpoint(Statement statement) throws SQLException { /* no-op */ }

    @Override
    public void createSchema(Statement statement, String prefix) throws SQLException {
        boolean partition = Config.getGlobal().POSTGRES_PARTITIONING;
        boolean lz4 = Config.getGlobal().POSTGRES_LZ4;

        statement.executeUpdate("CREATE TABLE IF NOT EXISTS " + prefix + "art_map (rowid bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, id integer, art varchar(255))");

        if (partition) {
            // Hot partitioned tables. Note: PG requires the partition key be in the PRIMARY KEY,
            // so we use composite (rowid, time). Identity column still works.
            statement.executeUpdate("CREATE TABLE IF NOT EXISTS " + prefix + "block (rowid bigint GENERATED BY DEFAULT AS IDENTITY, time integer NOT NULL, \"user\" integer, wid integer, x integer, y integer, z integer, type integer, data integer, meta bytea, blockdata bytea, action smallint, rolled_back smallint NOT NULL DEFAULT 0, PRIMARY KEY (time, rowid)) PARTITION BY RANGE (time)");
            statement.executeUpdate("CREATE TABLE IF NOT EXISTS " + prefix + "container (rowid bigint GENERATED BY DEFAULT AS IDENTITY, time integer NOT NULL, \"user\" integer, wid integer, x integer, y integer, z integer, type integer, data integer, amount integer, metadata bytea, action smallint, rolled_back smallint NOT NULL DEFAULT 0, PRIMARY KEY (time, rowid)) PARTITION BY RANGE (time)");
            // Default partitions catch any rows outside the explicit ranges (e.g. legacy data
            // pre-migration). Concrete weekly partitions are managed by PartitionService.
            statement.executeUpdate("CREATE TABLE IF NOT EXISTS " + prefix + "block_default PARTITION OF " + prefix + "block DEFAULT");
            statement.executeUpdate("CREATE TABLE IF NOT EXISTS " + prefix + "container_default PARTITION OF " + prefix + "container DEFAULT");
        }
        else {
            statement.executeUpdate("CREATE TABLE IF NOT EXISTS " + prefix + "block (rowid bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, time integer, \"user\" integer, wid integer, x integer, y integer, z integer, type integer, data integer, meta bytea, blockdata bytea, action smallint, rolled_back smallint)");
            statement.executeUpdate("CREATE TABLE IF NOT EXISTS " + prefix + "container (rowid bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, time integer, \"user\" integer, wid integer, x integer, y integer, z integer, type integer, data integer, amount integer, metadata bytea, action smallint, rolled_back smallint)");
        }

        statement.executeUpdate("CREATE TABLE IF NOT EXISTS " + prefix + "chat (rowid bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, time integer, \"user\" integer, wid integer, x integer, y integer, z integer, message varchar(16000))");
        statement.executeUpdate("CREATE TABLE IF NOT EXISTS " + prefix + "command (rowid bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, time integer, \"user\" integer, wid integer, x integer, y integer, z integer, message varchar(16000))");
        statement.executeUpdate("CREATE TABLE IF NOT EXISTS " + prefix + "item (rowid bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, time integer, \"user\" integer, wid integer, x integer, y integer, z integer, type integer, data bytea, amount integer, action smallint, rolled_back smallint)");
        statement.executeUpdate("CREATE TABLE IF NOT EXISTS " + prefix + "database_lock (rowid bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, status smallint, time integer)");
        statement.executeUpdate("CREATE TABLE IF NOT EXISTS " + prefix + "entity (rowid bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, time integer, data bytea)");
        statement.executeUpdate("CREATE TABLE IF NOT EXISTS " + prefix + "entity_map (rowid bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, id integer, entity varchar(255))");
        statement.executeUpdate("CREATE TABLE IF NOT EXISTS " + prefix + "material_map (rowid bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, id integer, material varchar(255))");
        statement.executeUpdate("CREATE TABLE IF NOT EXISTS " + prefix + "blockdata_map (rowid bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, id integer, data varchar(255))");
        statement.executeUpdate("CREATE TABLE IF NOT EXISTS " + prefix + "session (rowid bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, time integer, \"user\" integer, wid integer, x integer, y integer, z integer, action smallint)");
        statement.executeUpdate("CREATE TABLE IF NOT EXISTS " + prefix + "sign (rowid bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, time integer, \"user\" integer, wid integer, x integer, y integer, z integer, action smallint, color integer, color_secondary integer, data smallint, waxed smallint, face smallint, line_1 varchar(100), line_2 varchar(100), line_3 varchar(100), line_4 varchar(100), line_5 varchar(100), line_6 varchar(100), line_7 varchar(100), line_8 varchar(100))");
        statement.executeUpdate("CREATE TABLE IF NOT EXISTS " + prefix + "skull (rowid bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, time integer, owner varchar(255), skin varchar(255))");
        statement.executeUpdate("CREATE TABLE IF NOT EXISTS " + prefix + "user (rowid bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, time integer, \"user\" varchar(100), uuid varchar(64))");
        statement.executeUpdate("CREATE TABLE IF NOT EXISTS " + prefix + "username_log (rowid bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, time integer, uuid varchar(64), \"user\" varchar(100))");
        statement.executeUpdate("CREATE TABLE IF NOT EXISTS " + prefix + "version (rowid bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, time integer, version varchar(16))");
        statement.executeUpdate("CREATE TABLE IF NOT EXISTS " + prefix + "world (rowid bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, id integer, world varchar(255))");

        if (lz4) {
            tryAlterCompressionLz4(statement, prefix + "block",     "meta");
            tryAlterCompressionLz4(statement, prefix + "block",     "blockdata");
            tryAlterCompressionLz4(statement, prefix + "container", "metadata");
            tryAlterCompressionLz4(statement, prefix + "item",      "data");
            tryAlterCompressionLz4(statement, prefix + "entity",    "data");
        }

        // Indices. On partitioned parents, indices propagate to all attached partitions.
        idx(statement, prefix + "art_map",       "art_map_id_idx",          "(id)");
        idx(statement, prefix + "block",         "block_index",             "(wid, x, z, time)");
        idx(statement, prefix + "block",         "block_user_index",        "(\"user\", time)");
        idx(statement, prefix + "block",         "block_type_index",        "(type, time)");
        // BRIN on time for hot partitioned tables. Tiny index (~30 KB / 100M rows) and partition pruning
        // means BRIN is the right tool here, not a B-tree.
        tryBrin(statement, prefix + "block",     "block_time_brin",         "time");
        tryBrin(statement, prefix + "container", "container_time_brin",     "time");
        // Partial index for fast rollback lookups.
        try { statement.executeUpdate("CREATE INDEX IF NOT EXISTS " + prefix + "block_rb_partial_idx ON " + prefix + "block (wid, x, z, time) WHERE rolled_back = 0"); }
        catch (SQLException ignored) {}

        idx(statement, prefix + "blockdata_map", "blockdata_map_id_idx",    "(id)");
        idx(statement, prefix + "chat",          "chat_time_index",         "(time)");
        idx(statement, prefix + "chat",          "chat_user_index",         "(\"user\", time)");
        idx(statement, prefix + "chat",          "chat_wid_index",          "(wid, x, z, time)");
        idx(statement, prefix + "command",       "command_time_index",      "(time)");
        idx(statement, prefix + "command",       "command_user_index",      "(\"user\", time)");
        idx(statement, prefix + "command",       "command_wid_index",       "(wid, x, z, time)");
        idx(statement, prefix + "container",     "container_index",         "(wid, x, z, time)");
        idx(statement, prefix + "container",     "container_user_index",    "(\"user\", time)");
        idx(statement, prefix + "container",     "container_type_index",    "(type, time)");
        idx(statement, prefix + "item",          "item_index",              "(wid, x, z, time)");
        idx(statement, prefix + "item",          "item_user_index",         "(\"user\", time)");
        idx(statement, prefix + "item",          "item_type_index",         "(type, time)");
        idx(statement, prefix + "item",          "item_time_index",         "(time)");
        idx(statement, prefix + "entity_map",    "entity_map_id_idx",       "(id)");
        idx(statement, prefix + "material_map",  "material_map_id_idx",     "(id)");
        idx(statement, prefix + "session",       "session_index",           "(wid, x, z, time)");
        idx(statement, prefix + "session",       "session_action_index",    "(action, time)");
        idx(statement, prefix + "session",       "session_user_index",      "(\"user\", time)");
        idx(statement, prefix + "session",       "session_time_index",      "(time)");
        idx(statement, prefix + "sign",          "sign_index",              "(wid, x, z, time)");
        idx(statement, prefix + "sign",          "sign_user_index",         "(\"user\", time)");
        idx(statement, prefix + "sign",          "sign_time_index",         "(time)");
        idx(statement, prefix + "user",          "user_user_idx",           "(\"user\")");
        idx(statement, prefix + "user",          "user_uuid_idx",           "(uuid)");
        idx(statement, prefix + "username_log",  "username_log_uuid_idx",   "(uuid, \"user\")");
        idx(statement, prefix + "world",         "world_id_idx",            "(id)");
    }

    private static void idx(Statement s, String table, String name, String cols) throws SQLException {
        s.executeUpdate("CREATE INDEX IF NOT EXISTS " + name + " ON " + table + " " + cols);
    }

    private static void tryBrin(Statement s, String table, String name, String col) {
        try { s.executeUpdate("CREATE INDEX IF NOT EXISTS " + name + " ON " + table + " USING BRIN (" + col + ") WITH (pages_per_range = 32)"); }
        catch (SQLException e) {
            // BRIN unavailable; fall back to B-tree on time.
            try { s.executeUpdate("CREATE INDEX IF NOT EXISTS " + name + "_btree ON " + table + " (" + col + ")"); }
            catch (SQLException ignored) {}
        }
    }

    private static void tryAlterCompressionLz4(Statement s, String table, String column) {
        try { s.executeUpdate("ALTER TABLE " + table + " ALTER COLUMN " + column + " SET COMPRESSION lz4"); }
        catch (SQLException ignored) { /* PG <14 / no lz4 build: leave on default pglz */ }
    }

    @Override
    public int purgeOldRows(Connection connection, String prefixedTable, long beforeUnixSeconds, int chunkLimit) throws SQLException {
        String sql = "DELETE FROM " + prefixedTable
                   + " WHERE ctid IN (SELECT ctid FROM " + prefixedTable
                   + " WHERE time < ? ORDER BY time ASC LIMIT ?)";
        try (PreparedStatement ps = connection.prepareStatement(sql)) {
            ps.setLong(1, beforeUnixSeconds);
            ps.setInt(2, chunkLimit);
            return ps.executeUpdate();
        }
    }

    @Override
    public boolean supportsReturningClause() { return true; }

    @Override
    public boolean supportsOnConflict() { return true; }
}
