package net.coreprotect.database.dialect;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.Statement;

import net.coreprotect.consumer.Consumer;
import net.coreprotect.database.Backend;

public final class PostgresDialect implements Dialect {

    @Override
    public Backend backend() { return Backend.POSTGRES; }

    @Override
    public String driverClassName() { return "org.postgresql.Driver"; }

    @Override
    public String jdbcUrl(String host, int port, String database) {
        return "jdbc:postgresql://" + host + ":" + port + "/" + database;
    }

    @Override
    public void beginTransaction(Statement statement) {
        try {
            statement.executeUpdate("BEGIN");
        }
        catch (Exception e) {
            e.printStackTrace();
        }
    }

    @Override
    public void commitTransaction(Statement statement) throws Exception {
        try {
            statement.executeUpdate("COMMIT");
        }
        catch (Exception e) {
            e.printStackTrace();
        }
        finally {
            Consumer.transacting = false;
            Consumer.interrupt = false;
        }
    }

    @Override
    public void performCheckpoint(Statement statement) throws SQLException {
        // no-op; Postgres checkpoints are managed by the server.
    }

    /**
     * Postgres DDL. Choices that matter:
     * <ul>
     *   <li>{@code rowid} stays the column name to keep the runtime SQL identical to MySQL/SQLite.
     *       Postgres reserves no such word.</li>
     *   <li>Identity columns use {@code GENERATED BY DEFAULT AS IDENTITY}, the SQL-standard replacement
     *       for SERIAL. {@code rowid} is not in the INSERT VALUES list, so the identity always fires.</li>
     *   <li>{@code mediumblob}/{@code blob} ⇒ {@code bytea}. The pgjdbc driver accepts {@code byte[]}
     *       on a {@code setBytes(...)} or {@code setBinaryStream(...)} bound to {@code bytea} —
     *       no code change needed in {@code Consumer}.</li>
     *   <li>{@code tinyint} ⇒ {@code smallint}. CoreProtect already reads these as {@code int} from
     *       {@code ResultSet.getInt} so the widening is invisible.</li>
     *   <li>Indices created separately (PG has no inline {@code INDEX(...)} clause).</li>
     *   <li>Partial index {@code WHERE rolled_back = 0} cuts the rollback-lookup index in half once
     *       the table starts accumulating purged-but-not-yet-deleted rows.</li>
     *   <li>BRIN index on {@code time} for the hot tables — 30 KB instead of 3 GB on a 100M-row table,
     *       and range scans are sub-second because {@code time} is monotonically increasing.</li>
     * </ul>
     */
    @Override
    public void createSchema(Statement statement, String prefix) throws SQLException {
        // Tables (CREATE TABLE IF NOT EXISTS is supported since PG 9.1)
        statement.executeUpdate("CREATE TABLE IF NOT EXISTS " + prefix + "art_map (rowid bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, id integer, art varchar(255))");
        statement.executeUpdate("CREATE TABLE IF NOT EXISTS " + prefix + "block (rowid bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, time integer, \"user\" integer, wid integer, x integer, y integer, z integer, type integer, data integer, meta bytea, blockdata bytea, action smallint, rolled_back smallint)");
        statement.executeUpdate("CREATE TABLE IF NOT EXISTS " + prefix + "chat (rowid bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, time integer, \"user\" integer, wid integer, x integer, y integer, z integer, message varchar(16000))");
        statement.executeUpdate("CREATE TABLE IF NOT EXISTS " + prefix + "command (rowid bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, time integer, \"user\" integer, wid integer, x integer, y integer, z integer, message varchar(16000))");
        statement.executeUpdate("CREATE TABLE IF NOT EXISTS " + prefix + "container (rowid bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, time integer, \"user\" integer, wid integer, x integer, y integer, z integer, type integer, data integer, amount integer, metadata bytea, action smallint, rolled_back smallint)");
        statement.executeUpdate("CREATE TABLE IF NOT EXISTS " + prefix + "item (rowid bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, time integer, \"user\" integer, wid integer, x integer, y integer, z integer, type integer, data bytea, amount integer, action smallint, rolled_back smallint)");
        statement.executeUpdate("CREATE TABLE IF NOT EXISTS " + prefix + "database_lock (rowid bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, status smallint, time integer)");
        statement.executeUpdate("CREATE TABLE IF NOT EXISTS " + prefix + "entity (rowid bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, time integer, data bytea)");
        statement.executeUpdate("CREATE TABLE IF NOT EXISTS " + prefix + "entity_map (rowid bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, id integer, entity varchar(255))");
        statement.executeUpdate("CREATE TABLE IF NOT EXISTS " + prefix + "material_map (rowid bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, id integer, material varchar(255))");
        statement.executeUpdate("CREATE TABLE IF NOT EXISTS " + prefix + "blockdata_map (rowid bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, id integer, data varchar(255))");
        statement.executeUpdate("CREATE TABLE IF NOT EXISTS " + prefix + "session (rowid bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, time integer, \"user\" integer, wid integer, x integer, y integer, z integer, action smallint)");
        statement.executeUpdate("CREATE TABLE IF NOT EXISTS " + prefix + "sign (rowid bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, time integer, \"user\" integer, wid integer, x integer, y integer, z integer, action smallint, color integer, color_secondary integer, data smallint, waxed smallint, face smallint, line_1 varchar(100), line_2 varchar(100), line_3 varchar(100), line_4 varchar(100), line_5 varchar(100), line_6 varchar(100), line_7 varchar(100), line_8 varchar(100))");
        statement.executeUpdate("CREATE TABLE IF NOT EXISTS " + prefix + "skull (rowid bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, time integer, owner varchar(255), skin varchar(255))");
        // co_user table: name "co_user" itself is unreserved as a full identifier; only the bare column "user" needs quoting.
        statement.executeUpdate("CREATE TABLE IF NOT EXISTS " + prefix + "user (rowid bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, time integer, \"user\" varchar(100), uuid varchar(64))");
        statement.executeUpdate("CREATE TABLE IF NOT EXISTS " + prefix + "username_log (rowid bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, time integer, uuid varchar(64), \"user\" varchar(100))");
        statement.executeUpdate("CREATE TABLE IF NOT EXISTS " + prefix + "version (rowid bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, time integer, version varchar(16))");
        statement.executeUpdate("CREATE TABLE IF NOT EXISTS " + prefix + "world (rowid bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, id integer, world varchar(255))");

        // Compress hot blob columns transparently (PG 14+).
        // Older Postgres versions ignore the unknown option silently? No — they'd error. Wrap in try.
        tryAlterCompressionLz4(statement, prefix + "block",     "meta");
        tryAlterCompressionLz4(statement, prefix + "block",     "blockdata");
        tryAlterCompressionLz4(statement, prefix + "container", "metadata");
        tryAlterCompressionLz4(statement, prefix + "item",      "data");
        tryAlterCompressionLz4(statement, prefix + "entity",    "data");

        // Indices
        idx(statement, prefix + "art_map",        "art_map_id_idx",            "(id)");
        idx(statement, prefix + "block",          "block_index",               "(wid, x, z, time)");
        idx(statement, prefix + "block",          "block_user_index",          "(\"user\", time)");
        idx(statement, prefix + "block",          "block_type_index",          "(type, time)");
        // BRIN on time — tiny + perfect for monotonic columns.
        try {
            statement.executeUpdate("CREATE INDEX IF NOT EXISTS " + prefix + "block_time_brin ON " + prefix + "block USING BRIN (time) WITH (pages_per_range = 32)");
        }
        catch (SQLException e) {
            // BRIN exists since PG 9.5 — but if it fails, fall back to a regular B-tree.
            idx(statement, prefix + "block", "block_time_index", "(time)");
        }
        // Partial index on rolled_back=0 for fast rollback lookups.
        try {
            statement.executeUpdate("CREATE INDEX IF NOT EXISTS " + prefix + "block_rb_partial_idx ON " + prefix + "block (wid, x, z, time) WHERE rolled_back = 0");
        }
        catch (SQLException ignored) {}

        idx(statement, prefix + "blockdata_map",  "blockdata_map_id_idx",      "(id)");
        idx(statement, prefix + "chat",           "chat_time_index",           "(time)");
        idx(statement, prefix + "chat",           "chat_user_index",           "(\"user\", time)");
        idx(statement, prefix + "chat",           "chat_wid_index",            "(wid, x, z, time)");
        idx(statement, prefix + "command",        "command_time_index",        "(time)");
        idx(statement, prefix + "command",        "command_user_index",        "(\"user\", time)");
        idx(statement, prefix + "command",        "command_wid_index",         "(wid, x, z, time)");
        idx(statement, prefix + "container",      "container_index",           "(wid, x, z, time)");
        idx(statement, prefix + "container",      "container_user_index",      "(\"user\", time)");
        idx(statement, prefix + "container",      "container_type_index",      "(type, time)");
        try {
            statement.executeUpdate("CREATE INDEX IF NOT EXISTS " + prefix + "container_time_brin ON " + prefix + "container USING BRIN (time) WITH (pages_per_range = 32)");
        }
        catch (SQLException ignored) {
            idx(statement, prefix + "container", "container_time_index", "(time)");
        }
        idx(statement, prefix + "item",           "item_index",                "(wid, x, z, time)");
        idx(statement, prefix + "item",           "item_user_index",           "(\"user\", time)");
        idx(statement, prefix + "item",           "item_type_index",           "(type, time)");
        idx(statement, prefix + "item",           "item_time_index",           "(time)");
        idx(statement, prefix + "entity_map",     "entity_map_id_idx",         "(id)");
        idx(statement, prefix + "material_map",   "material_map_id_idx",       "(id)");
        idx(statement, prefix + "session",        "session_index",             "(wid, x, z, time)");
        idx(statement, prefix + "session",        "session_action_index",      "(action, time)");
        idx(statement, prefix + "session",        "session_user_index",        "(\"user\", time)");
        idx(statement, prefix + "session",        "session_time_index",        "(time)");
        idx(statement, prefix + "sign",           "sign_index",                "(wid, x, z, time)");
        idx(statement, prefix + "sign",           "sign_user_index",           "(\"user\", time)");
        idx(statement, prefix + "sign",           "sign_time_index",           "(time)");
        // Note: "user" table needs quoted name because user is a PG reserved word.
        idx(statement, prefix + "user",       "user_user_idx",             "(\"user\")");
        idx(statement, prefix + "user",       "user_uuid_idx",             "(uuid)");
        idx(statement, prefix + "username_log",   "username_log_uuid_idx",     "(uuid, \"user\")");
        idx(statement, prefix + "world",          "world_id_idx",              "(id)");
    }

    private static void idx(Statement s, String table, String name, String cols) throws SQLException {
        s.executeUpdate("CREATE INDEX IF NOT EXISTS " + name + " ON " + table + " " + cols);
    }

    private static void tryAlterCompressionLz4(Statement s, String table, String column) {
        try {
            s.executeUpdate("ALTER TABLE " + table + " ALTER COLUMN " + column + " SET COMPRESSION lz4");
        }
        catch (SQLException ignored) {
            // PG < 14 or build without lz4: fall back to default pglz, which still works.
        }
    }

    @Override
    public int purgeOldRows(Connection connection, String prefixedTable, long beforeUnixSeconds, int chunkLimit) throws SQLException {
        // PG supports `DELETE ... WHERE ctid IN (SELECT ctid ... LIMIT N)` for chunked purges.
        String sql = "DELETE FROM " + prefixedTable
                   + " WHERE ctid IN (SELECT ctid FROM " + prefixedTable
                   + " WHERE time < ? ORDER BY time ASC LIMIT ?)";
        try (PreparedStatement ps = connection.prepareStatement(sql)) {
            ps.setLong(1, beforeUnixSeconds);
            ps.setInt(2, chunkLimit);
            return ps.executeUpdate();
        }
    }

    @Override
    public boolean supportsReturningClause() { return true; }

    @Override
    public boolean supportsOnConflict() { return true; }
}
